"""empty message

Revision ID: fe1946c1ea9a
Revises: 9a9cf638f8af
Create Date: 2020-07-19 04:05:18.865098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe1946c1ea9a'
down_revision = '9a9cf638f8af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_post',
    sa.Column('id_post', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('updated_at', sa.Date(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('count_like', sa.String(length=128), nullable=False),
    sa.Column('count_dislike', sa.Integer(), nullable=False),
    sa.Column('fg_user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fg_user'], ['tb_user.id'], ),
    sa.PrimaryKeyConstraint('id_post')
    )
    op.create_table('tb_comment',
    sa.Column('id_comment', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('updated_at', sa.Date(), nullable=False),
    sa.Column('fg_user', sa.Integer(), nullable=False),
    sa.Column('fg_comment', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fg_comment'], ['tb_post.id_post'], ),
    sa.ForeignKeyConstraint(['fg_user'], ['tb_user.id'], ),
    sa.PrimaryKeyConstraint('id_comment')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_comment')
    op.drop_table('tb_post')
    # ### end Alembic commands ###
